<a href="https://colab.research.google.com/github/Priya-ssharma/Finance_Research_Agent/blob/main/FinanceResearchAgent_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
project_name = "FinanceResearchAgent"
company_name = "Reliance Industries Limited"

print("Project:", project_name)
print("Research company:", company_name)
print("Environment: Google Colab")
print("Setup status: Started successfully!")

Project: FinanceResearchAgent
Research company: Reliance Industries Limited
Environment: Google Colab
Setup status: Started successfully!

In [5]:

from pathlib import Path

content = """# FinanceResearchAgent — Source Register

## Research Subject
Reliance Industries Limited (RIL)

## Reporting Period
Financial Year 2025–26
1 April 2025 to 31 March 2026

## Primary Sources

### 1. Integrated Annual Report
- Source: Reliance Industries Limited
- Period: FY 2025–26
- URL: https://www.ril.com/ar2025-26/index.html
- Intended use: Business overview, strategy, risks, governance,
  financial review and sustainability disclosures.

### 2. Consolidated Financial Statements
- Source: Reliance Industries Limited
- Period ended: 31 March 2026
- Intended use: Consolidated balance sheet, profit and loss,
  cash flows, notes and independent auditor's report.

### 3. Quarterly and Full-Year Financial Results
- Source: Reliance Industries Limited
- Period: Q1, Q2, Q3 and Q4 FY 2025–26
- URL: https://www.ril.com/investors/financial-reporting

## Evidence Rules
- Prefer official company disclosures.
- Record reporting periods and units for every metric.
- Preserve source URLs and page references.
- Distinguish reported facts from analysis.
- Flag missing or unverified information.
- Do not present historical figures as live market data.
- Do not provide personalized investment advice.

## Current Status
Official source documents collected.
Automated extraction and validation are pending.
"""

Path("source_register.md").write_text(content, encoding="utf-8")
print("Source register created successfully!")

Source register created successfully!

In [7]:
%pip -q install pypdf

from pathlib import Path
from pypdf import PdfReader

pdf_path = Path("/content/RIL-Integrated-Annual-Report-2025-26.pdf")

if pdf_path.exists():
    reader = PdfReader(str(pdf_path))
    print("PDF loaded successfully!")
    print("Total pages:", len(reader.pages))

    text = reader.pages[5].extract_text() or ""
    print("\n--- EXTRACTED REPORT TEXT ---\n")
    print(text[:3000])
else:
    print("PDF not found. Please check the filename in Colab's Files panel.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.1/405.1 kB 11.1 MB/s eta 0:00:00
PDF loaded successfully!
Total pages: 147

--- EXTRACTED REPORT TEXT ---

Reliance Industries Limited Integrated Annual Report 2025-26
8 9
Management Discussion and Analysis -  Business OverviewManagement Discussion and Analysis
Movement in Key
Financial Ratios
The Debt Service Coverage Ratio
increased from 2.06 in FY 2024-25
to 4.03 in FY 2025-26, due to lower
finance cost and principal repayments
of loans during the year.
The Net Profit Margin increased
from 6.3% in FY 2024-25 to 8.0% in
FY 2025-26, due to higher net profit.
Return on Capital Employed increased
from 14.6% in FY 2024-25 to 20.7% in
FY 2025-26, due to higher profit and
reduction in capital employed.
Long Term Debt to Working Capital
increased from 7.53 in FY 2024-25
to 17.12 in FY 2025-26, due to
higher debt and efficient working
capital management.
Interest Coverage Ratio increased
from 5.59 in FY 2024-25 to 8.83 in
FY 2025-26, due to higher operating
profit along with lower finance costs.
The Return on Net Worth* improved to
10.1% in FY 2025-26 as against 8.2%
in previous year due to increase in net
profit during the year.
*Adjusted for CWIP and revaluation
Liquidity and Capital
Resources
Macro Environment
FY 2025-26 saw heightened volatility
in financial markets amid tariff
uncertainty and global geopolitics.
In India, the first half of the financial
year saw RBI easing monetary policy
leading to an environment of softening
domestic yields with 10y G-sec yields
easing towards 6.25%. The second
half of the year saw yields reversing
upwards as RBI shifted its stance from
accommodative to neutral, causing
10y G-sec yields to harden towards
7%. Rupee came under downward
pressure on account of FPI outflows,
rising trade deficit and fresh tensions in
Middle East.
Fund Raising
The year 2025 unfolded against
a backdrop of heightened market
fluctuations. Trade dynamics shifted
as US tariff moves realigned global
supply chains. Despite this turbulent
market environment, the Company
was able to raise financing across
currencies and products at competitive
cost for long tenors to finance capital
expenditure and to refinance its
scheduled maturities.
Offshore Facilities
Samurai Loan - JPY 91.9 Billion
(~$625 Million Equivalent)
The Company tied up these facilities to
refinance its JPY debt maturing during
the year. The transaction witnessed
participation from 10 Japanese and
Taiwanese banks. This was the largest
Samurai loan ever by an Indian corporate
and the third-largest ever by an
Asian corporate.
ECA-supported Facilities
(~$500 Million Equivalent)
RIL tied up ~US$ 500 million equivalent
KSURE (Korean Export Credit Agency)
supported untied facilities to finance
capital expenditure of the Company.
This is KSURE’s first untied facility
for any corporate globally.
NEXI-supported Facilities
(~$600 Million Equivalent)
RIL tied up ~$600 million equivalent
NEXI (Japanese Export Credit Agency)
supported untied facilities to
finance certain expenses relating to
the Company’s solar photovoltaics (PV)

Next step — Build a searchable financial research dataset

In [8]:

# FinanceResearchAgent — Step 2
# Extract all PDF pages and locate relevant financial sections

import json
import re
from pathlib import Path
from pypdf import PdfReader

pdf_path = Path("/content/RIL-Integrated-Annual-Report-2025-26.pdf")
output_dir = Path("/content/finance_research_output")
output_dir.mkdir(parents=True, exist_ok=True)

reader = PdfReader(str(pdf_path))

records = []

for page_index, page in enumerate(reader.pages):
    page_text = page.extract_text() or ""

    records.append({
        "company": "Reliance Industries Limited",
        "reporting_period": "FY 2025-26",
        "pdf_page": page_index + 1,
        "source_file": pdf_path.name,
        "source_url": "https://www.ril.com/ar2025-26/index.html",
        "text": page_text
    })

# Save extracted text with page references
json_path = output_dir / "ril_annual_report_pages.json"

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

# Search for financial research topics
topics = {
    "Revenue": r"\brevenue\b",
    "EBITDA": r"\bEBITDA\b",
    "Profit": r"\bprofit\b|\bPAT\b",
    "Debt": r"\bdebt\b",
    "Cash Flow": r"cash flow",
    "Financial Ratios": r"financial ratios|interest coverage|debt service coverage|net profit margin|return on capital employed",
    "Risk": r"\brisk\b|\brisks\b",
    "Business Segments": r"retail|digital services|oil to chemicals|oil and gas"
}

print("Total PDF pages:", len(records))
print("Pages with extractable text:",
      sum(bool(r["text"].strip()) for r in records))
print("\n--- SEARCH RESULTS ---")

for topic, pattern in topics.items():
    matches = [
        r["pdf_page"] for r in records
        if re.search(pattern, r["text"], flags=re.IGNORECASE)
    ]

    print(f"{topic}: {len(matches)} matching pages")
    print("PDF page numbers:", matches[:15])

print("\nExtracted text saved to:", json_path)
print("Dataset creation completed!")

Total PDF pages: 147
Pages with extractable text: 147

--- SEARCH RESULTS ---
Revenue: 39 matching pages
PDF page numbers: [3, 5, 6, 7, 8, 9, 11, 13, 14, 16, 21, 41, 42, 51, 52]
EBITDA: 11 matching pages
PDF page numbers: [3, 4, 5, 6, 7, 9, 11, 13, 14, 41, 42]
Profit: 57 matching pages
PDF page numbers: [4, 5, 6, 41, 42, 46, 52, 54, 59, 61, 62, 63, 64, 68, 70]
Debt: 19 matching pages
PDF page numbers: [3, 5, 6, 16, 57, 60, 72, 75, 77, 89, 90, 93, 102, 112, 115]
Cash Flow: 30 matching pages
PDF page numbers: [6, 35, 52, 53, 54, 60, 61, 62, 63, 70, 73, 75, 89, 90, 91]
Financial Ratios: 4 matching pages
PDF page numbers: [5, 6, 57, 93]
Risk: 55 matching pages
PDF page numbers: [2, 5, 6, 7, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Business Segments: 69 matching pages
PDF page numbers: [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17]

Extracted text saved to: /content/finance_research_output/ril_annual_report_pages.json
Dataset creation completed!

Step 3 — Build a financial evidence table

In [9]:

# FinanceResearchAgent — Step 3
# Find evidence for specific financial metrics

import json
import re
import pandas as pd
from pathlib import Path

json_path = Path(
    "/content/finance_research_output/ril_annual_report_pages.json"
)

with open(json_path, "r", encoding="utf-8") as f:
    records = json.load(f)

metric_patterns = {
    "Debt Service Coverage Ratio": r"Debt Service Coverage Ratio",
    "Net Profit Margin": r"Net Profit Margin",
    "Return on Capital Employed": r"Return on Capital Employed",
    "Long Term Debt to Working Capital": r"Long Term Debt to Working Capital",
    "Interest Coverage Ratio": r"Interest Coverage Ratio",
    "Return on Net Worth": r"Return on Net Worth"
}

evidence = []

for metric, pattern in metric_patterns.items():
    found = False

    for record in records:
        text = record["text"]

        for match in re.finditer(pattern, text, re.IGNORECASE):
            start = max(0, match.start() - 100)
            end = min(len(text), match.end() + 350)

            evidence.append({
                "metric": metric,
                "pdf_page": record["pdf_page"],
                "reporting_period": record["reporting_period"],
                "source_file": record["source_file"],
                "source_url": record["source_url"],
                "evidence_text": text[start:end].replace("\n", " ").strip()
            })

            found = True

    if not found:
        print("No match found for:", metric)

df = pd.DataFrame(evidence)

if not df.empty:
    output_path = Path(
        "/content/finance_research_output/financial_metric_evidence.csv"
    )
    df.to_csv(output_path, index=False)

    print("Evidence rows found:", len(df))
    print("Saved to:", output_path)
    display(df[["metric", "pdf_page", "evidence_text"]])
else:
    print("No evidence extracted. We will inspect the PDF text.")

Evidence rows found: 15
Saved to: /content/finance_research_output/financial_metric_evidence.csv

,metric,pdf_page,evidence_text
0,Debt Service Coverage Ratio,6,alysis - Business OverviewManagement Discussi...
1,Debt Service Coverage Ratio,93,s 2025-26 \t 2024-25\t %\tChanges 1 Current Ra...
2,Debt Service Coverage Ratio,93,Return on Capital Employed (%) c 20.7% 14.6% 4...
3,Debt Service Coverage Ratio,93,la 1 Current Ratio Current Assets Current Liab...
4,Net Profit Margin,5,0.75:1 EBITDA/Gross Turnover (%) - 17.7 1...
5,Net Profit Margin,6,"3 in FY 2025-26, due to lower finance cost an..."
6,Net Profit Margin,93,.74 (7.6) 7 Trade Payables Turnover Ratio 3.39...
7,Net Profit Margin,93,l Turnover Ratio Value of Sales & Services Wor...
8,Return on Capital Employed,6,Profit Margin increased from 6.3% in FY 2024...
9,Return on Capital Employed,93,3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -...
10,Return on Capital Employed,93,repayments of loans during the year. b)\t Net...
11,Return on Capital Employed,93,ent Assets - Current Liabilities) 9 Net Profit...
12,Long Term Debt to Working Capital,6,".6% in FY 2024-25 to 20.7% in FY 2025-26, due..."
13,Interest Coverage Ratio,6,"FY 2024-25 to 17.12 in FY 2025-26, due to hi..."
14,Return on Net Worth,6,"2024-25 to 8.83 in FY 2025-26, due to higher ..."

Step 4 — Fix the metric extraction

In [10]:

# FinanceResearchAgent — Step 4
# Improve financial metric evidence extraction

import json
import re
import pandas as pd
from pathlib import Path

json_path = Path(
    "/content/finance_research_output/ril_annual_report_pages.json"
)

with open(json_path, "r", encoding="utf-8") as f:
    records = json.load(f)

metrics = [
    "Debt Service Coverage Ratio",
    "Net Profit Margin",
    "Return on Capital Employed",
    "Long Term Debt to Working Capital",
    "Interest Coverage Ratio",
    "Return on Net Worth"
]

results = []

for record in records:
    text = re.sub(r"\s+", " ", record["text"]).strip()

    for metric in metrics:
        # Find each exact metric name
        for match in re.finditer(re.escape(metric), text, re.IGNORECASE):
            # Capture a limited window around the match
            start = max(0, match.start() - 120)
            end = min(len(text), match.end() + 220)
            snippet = text[start:end].strip()

            results.append({
                "metric": metric,
                "pdf_page": record["pdf_page"],
                "evidence_text": snippet,
                "source_file": record["source_file"],
                "source_url": record["source_url"],
                "reporting_period": record["reporting_period"],
                "validation_status": "Needs manual verification"
            })

df = pd.DataFrame(results)

output_path = Path(
    "/content/finance_research_output/financial_metric_evidence_v2.csv"
)

df.to_csv(output_path, index=False)

print("Evidence passages:", len(df))
print("Saved to:", output_path)

display(df[["metric", "pdf_page", "evidence_text"]])

Evidence passages: 16
Saved to: /content/finance_research_output/financial_metric_evidence_v2.csv

,metric,pdf_page,evidence_text
0,Net Profit Margin,5,0.34:1 0.36:1 0.75:1 0.74:1 0.75:1 0.75:1 EBIT...
1,Debt Service Coverage Ratio,6,ment Discussion and Analysis - Business Overvi...
2,Net Profit Margin,6,"6 in FY 2024-25 to 4.03 in FY 2025-26, due to ..."
3,Return on Capital Employed,6,ring the year. The Net Profit Margin increased...
4,Long Term Debt to Working Capital,6,oyed increased from 14.6% in FY 2024-25 to 20....
5,Interest Coverage Ratio,6,increased from 7.53 in FY 2024-25 to 17.12 in ...
6,Return on Net Worth,6,eased from 5.59 in FY 2024-25 to 8.83 in FY 20...
7,Debt Service Coverage Ratio,93,sis: Sr. No. Particulars 2025-26 2024-25 % Cha...
8,Debt Service Coverage Ratio,93,) b 8.0% 6.3% 27.0 10 Return on Capital Employ...
9,Debt Service Coverage Ratio,93,o. Particulars Formula 1 Current Ratio Current...
10,Net Profit Margin,93,nover Ratio 33.93 36.74 (7.6) 7 Trade Payables...
11,Net Profit Margin,93,) Debt Service Coverage Ratio increased due to...
12,Net Profit Margin,93,ayables 8 Net Capital Turnover Ratio Value of ...
13,Return on Capital Employed,93,bles Turnover Ratio 3.39 3.61 (6.1) 8 Net Capi...
14,Return on Capital Employed,93,nce cost and principal repayments of loans dur...
15,Return on Capital Employed,93,orking Capital (Current Assets - Current Liabi...

Step 5 — Inspect the actual report text

In [11]:

# FinanceResearchAgent — Step 5
# Inspect the source pages before validating metrics

import json
from pathlib import Path

json_path = Path(
    "/content/finance_research_output/ril_annual_report_pages.json"
)

with open(json_path, "r", encoding="utf-8") as f:
    records = json.load(f)

pages_to_inspect = [6, 93]

for page_number in pages_to_inspect:
    record = next(
        (r for r in records if r["pdf_page"] == page_number),
        None
    )

    print("\n" + "=" * 80)
    print(f"PDF PAGE {page_number}")
    print("=" * 80)

    if record:
        print(record["text"])
    else:
        print("Page not found.")

================================================================================
PDF PAGE 6
================================================================================
Reliance Industries Limited Integrated Annual Report 2025-26
8 9
Management Discussion and Analysis -  Business OverviewManagement Discussion and Analysis
Movement in Key
Financial Ratios
The Debt Service Coverage Ratio
increased from 2.06 in FY 2024-25
to 4.03 in FY 2025-26, due to lower
finance cost and principal repayments
of loans during the year.
The Net Profit Margin increased
from 6.3% in FY 2024-25 to 8.0% in
FY 2025-26, due to higher net profit.
Return on Capital Employed increased
from 14.6% in FY 2024-25 to 20.7% in
FY 2025-26, due to higher profit and
reduction in capital employed.
Long Term Debt to Working Capital
increased from 7.53 in FY 2024-25
to 17.12 in FY 2025-26, due to
higher debt and efficient working
capital management.
Interest Coverage Ratio increased
from 5.59 in FY 2024-25 to 8.83 in
FY 2025-26, due to higher operating
profit along with lower finance costs.
The Return on Net Worth* improved to
10.1% in FY 2025-26 as against 8.2%
in previous year due to increase in net
profit during the year.
*Adjusted for CWIP and revaluation
Liquidity and Capital
Resources
Macro Environment
FY 2025-26 saw heightened volatility
in financial markets amid tariff
uncertainty and global geopolitics.
In India, the first half of the financial
year saw RBI easing monetary policy
leading to an environment of softening
domestic yields with 10y G-sec yields
easing towards 6.25%. The second
half of the year saw yields reversing
upwards as RBI shifted its stance from
accommodative to neutral, causing
10y G-sec yields to harden towards
7%. Rupee came under downward
pressure on account of FPI outflows,
rising trade deficit and fresh tensions in
Middle East.
Fund Raising
The year 2025 unfolded against
a backdrop of heightened market
fluctuations. Trade dynamics shifted
as US tariff moves realigned global
supply chains. Despite this turbulent
market environment, the Company
was able to raise financing across
currencies and products at competitive
cost for long tenors to finance capital
expenditure and to refinance its
scheduled maturities.
Offshore Facilities
Samurai Loan - JPY 91.9 Billion
(~$625 Million Equivalent)
The Company tied up these facilities to
refinance its JPY debt maturing during
the year. The transaction witnessed
participation from 10 Japanese and
Taiwanese banks. This was the largest
Samurai loan ever by an Indian corporate
and the third-largest ever by an
Asian corporate.
ECA-supported Facilities
(~$500 Million Equivalent)
RIL tied up ~US$ 500 million equivalent
KSURE (Korean Export Credit Agency)
supported untied facilities to finance
capital expenditure of the Company.
This is KSURE’s first untied facility
for any corporate globally.
NEXI-supported Facilities
(~$600 Million Equivalent)
RIL tied up ~$600 million equivalent
NEXI (Japanese Export Credit Agency)
supported untied facilities to
finance certain expenses relating to
the Company’s solar photovoltaics (PV)
and battery gigafactories. This is NEXI's
first untied facility for any corporate
globally. The facility has the longest
average tenor for any Export Credit
Agency supported facility globally.
Liquidity Management
Reliance prioritises liquidity
management by maintaining a strong
cash reserve to safeguard operations
against sudden market volatility.
Further, by maintaining sufficient
undrawn credit lines, the Group ensures
it can consistently meet its short-term
obligations. RIL utilises diverse trade
financing and structured products
to optimise its working capital. RIL’s
investment strategy is continuously
refined to balance stable returns with
immediate fund accessibility.
Credit Rating
S&P raised RIL's rating from BBB+
to A- in December 2025 reflecting
rising contribution from less cyclical,
consumer-facing businesses resulting
in improved earnings stability. The
rating upgrade will provide RIL access
to new pools of capital at finer spreads.
Instrument Rating Agency Ratings Remarks
International Debt S&P A- Two notches above India's sovereign rating
International Debt Moody's Baa2 One notch above India's sovereign rating
Long-term Debt CRISIL AAA (Stable) Highest rating by CRISIL
Long-term Debt CARE AAA (Stable) Highest rating by CARE
Long-term Debt ICRA AAA (Stable) Highest rating by ICRA
Long-term Debt India Ratings AAA (Stable) Highest rating by India Ratings
Way Forward
RIL’s commitment to enhancing shareholder value is anchored in its diversified
business portfolio, resilient cash flows and a robust balance sheet. The
Company's financial architecture is defined by active monitoring of market
trends and swift response to shifting macroeconomic conditions. RIL will
continue to explore sophisticated financing structures to support expansion
across both emerging and established verticals. Integral to this trajectory is a
resolute adherence to capital allocation rigour, ensuring that financial strategy is
reinforced by comprehensive risk mitigation and optimal balance sheet structure.
- Financial Performance and Review
Retail
Reliance Retail is the largest and the most profitable
retailer in India, operating in an integrated retail
ecosystem that combines physical stores, digital
commerce and distribution platforms. Today,
Reliance Retail is positioned as India’s largest omni-
channel retailer with the scale and capabilities to
serve customers seamlessly across touchpoints.
Reliance Retail's operating model prioritises
accessibility, affordability and availability, while
fulfilling the daily needs of millions across every
consumption basket.
Strategic
Objective
Strengthen Reliance Retail's
position as India's largest
and most trusted retailer by
democratizing access to quality
products and experiences for
every Indian. Reliance Retail
would harness technology
and innovation to redefine the
future of Indian retail, creating
lasting value for consumers,
communities, and the nation.
Industry Overview
India is one of the world’s fastest-
growing retail markets, and expected
to become the third-largest by 2030.
The country’s retail sector is entering
a transformative phase, fuelled by the
rising purchasing power of a young,
digitally savvy, and aspiring population.
The retail sector, estimated at US$ 1.07
trillion in 2024, is projected to reach
US$ 1.93 trillion by 2030, growing at a
CAGR of 10% according to Deloitte-
FICCI 2025 report. Growth is being
led by the expansion of physical
stores in underpenetrated regions and
the continued rise of e-commerce,
enabling seamless, anytime access for
consumers. E-commerce penetration,
estimated at 7% in 2024 is expected to
double to 14% by 2030 ably supported
by omni-channel strategies adopted
by retailers.
Key Trends Shaping
the Market
Rapid growth of quick commerce
delivery models is bringing a structural
shift in the way consumers shop in India.
Premiumisation is transforming Indian
retail from mass consumption to
value-driven, high-quality experiences
across categories.
Fast fashion is reshaping demand
patterns, with shorter trend cycles
and faster inventory turns driving
apparel consumption. Social media and
platform-led discovery are accelerating
impulse purchases and increasing
wardrobe turnover frequency.
Business
Performance
During the year, Reliance Retail
recorded Gross Revenue of H 3,71,085
crore, reflecting a growth of 12.1%
over the previous year. EBITDA for the
year stood at H 27,034 crore, translating
into an EBITDA margin of 8.2%, slight
moderation due to growing contribution
of hyper-local commerce.
20,160
RETAIL STORES
78.3 Million sq. ft.
RETAIL AREA
387 Million
REGISTERED CUSTOMER BASE
~1.9 Billion
TRANSACTIONS
2,90,293
PEOPLE

================================================================================
PDF PAGE 93
================================================================================
Reliance Industries Limited Integrated Annual Report 2025-26
182 183
Standalone Financial Statements
Notes
To the Standalone Financial Statements for the year ended 31st March, 2026
40.	 Ratio	Analysis:
Sr.
No. Particulars 2025-26 	 2024-25	 %	Changes
1 Current Ratio 0.99 1.05 (5.7)
2 Debt-Equity Ratio 0.41 0.37 10.8
3 Debt Service Coverage Ratio a 4.03 2.06 95.6
4 Return on Equity (%) 8.5% 7.3% 17.0
5 Inventory Turnover Ratio 5.91 6.85 (13.7)
6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6)
7 Trade Payables Turnover Ratio 3.39 3.61 (6.1)
8 Net Capital Turnover Ratio -* 47.92 -
9 Net Profit Margin (%) b 8.0% 6.3% 27.0
10 Return on Capital Employed (%) c 20.7% 14.6% 41.0
11 Return on Investment (%) 9.5% 10.3% (7.7)
 a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year.
 b)	 Net	Profit	Margin increased due to higher net profit.
 c) Return on Capital Employed increased due to higher profit and reduction in capital employed.
 * Net working capital is negative.
	 40.1	 Formula	for	computation	of	ratios	are	as	follows:
Sr. No. Particulars Formula
1 Current Ratio Current Assets
Current Liabilities
2 Debt-Equity Ratio Total Debt
Total Equity
3 Debt Service Coverage Ratio Earnings before Interest and Tax
Interest Expense + Principal Repayments made during the year for long
term loans
4 Return on Equity (%) Profit After Tax
Average Net Worth
5 Inventory Turnover Ratio Cost of Goods Sold (Cost of Material Consumed + Purchases +
Changes in Inventory + Manufacturing Expenses)
Average Inventories of Finished Goods, Stock‑in‑Process and
Stock-in-Trade
6 Trade Receivables Turnover Ratio Value of Sales & Services
Average Trade Receivables
7 Trade Payables Turnover Ratio Cost of Materials Consumed (after adjustment of RM Inventory) +
Purchases of Stock‑in‑Trade + Other Expenses
Average Trade Payables
8 Net Capital Turnover Ratio Value of Sales & Services
Working Capital (Current Assets - Current Liabilities)
9 Net Profit Margin Profit After Tax
Value of Sales & Services
10 Return on Capital Employed Profit After Tax + Deferred Tax Expense/(Income) + Finance Cost (‑)
Other Income from Cash & Other Marketable Securities
Average Capital Employed**
11 Return on Investment Other Income (Excluding Dividend)
Average Cash, Cash Equivalents & Other Marketable Securities
  **  Capital employed includes Equity, Borrowings, Deferred Tax Liabilities, Creditor for Capital Expenditure and reduced by Investments, Cash and
Cash Equivalents, Capital Work-in-Progress and Intangible Assets under Development.
41.	 Other	Statutory	Information
	 (i)	 	Balances	outstanding	with	Nature	of	transaction	with	struck	off	companies	as	per	section	248	of	the	Companies	Act,	2013:
Sr.
No. Name	of	struck	off	company	 Nature of transactions with  struck-off 	company Balance outstanding  (K in crore) Relationship with the Struck off	company
1 Prasad Textiles Private Limited (H 2,772) Advance Received from Customer - NA
2 ARJ Infrastructure Private Limited (H 64,400) Trade Payables - NA
3 EMS Network Private Limited (H 25,543) Trade Payables - NA
4 Vishesh Corporation Private Limited (H 3,64,985) Trade Payables - NA
5 Gyan Packaging Industries Private Limited
(H 24,66,705)
Trade Receivable - NA
6 Mascot Global Private Limited (H 500) Trade Receivable - NA
7 Merchants Textile Industries Private Limited
(H 3,12,549)
Trade Receivable - NA
8 Venus Extrusions Private Limited (H 36,27,325) Trade Receivable - NA
 (ii)   The Company has not advanced or loaned or invested funds to any other persons or entities, including foreign entities
(Intermediaries) with the understanding that the Intermediary shall:
  (a)  Directly or indirectly lend or invest in other persons or entities identified in any manner whatsoever by or on behalf of the
company (Ultimate Beneficiaries) or
  (b) Provide any guarantee, security or the like to or on behalf of the Ultimate Beneficiaries.
 (iii)   The Company has not received any fund from any person(s) or entity(ies), including foreign entities (Funding Party) with the
understanding (whether recorded in writing or otherwise) that the Company shall:
  (a)  Directly or indirectly lend or invest in other persons or entities identified in any manner whatsoever by or on behalf of the
Funding Party (Ultimate Beneficiaries) or
  (b) Provide any guarantee, security or the like on behalf of the Ultimate Beneficiaries.
 (iv)   The Company does not have any transaction which is not recorded in the books of account that has been surrendered or disclosed
as income during the year in the tax assessments under the Income‑tax Act, 1961.
42.	 Events	after	the	Reporting	Period
  The Board of Directors have recommended dividend of H 6 per fully paid up equity share of H 10/‑ each for the financial year 2025‑26
aggregating H 8,119 crore.
43.	  The figures for the corresponding previous year have been regrouped / reclassified wherever necessary, to make them
comparable.
44.	 Approval	of	Financial	Statements
 The financial statements were approved for issue by the Board of Directors on April 24, 2026.
As per our Report of even date
For Deloitte Haskins & Sells LLP
Chartered Accountants
(Registration No.
117366W/W‑100018)
For Chaturvedi & Shah LLP
Chartered Accountants
(Registration No.
101720W/W‑100355)
Srikanth Venkatachari
Chief Financial Officer
Abhijit A. Damle
Partner
Membership No. 102912
Sandesh Ladha
Partner
Membership No. 047841
Savithri Parekh
Company Secretary
Date: April 24, 2026
For and on behalf of the Board
M.D. Ambani
DIN: 00001695
N.R. Meswani
DIN: 00001620
H.R. Meswani
DIN: 00001623
P.M.S. Prasad
DIN: 00012144
Anant M. Ambani
DIN: 07945702
Akash M. Ambani
DIN: 06984194
Isha M. Ambani
DIN: 06984175
Dr. Shumeet Banerji
DIN: 02787784
Arundhati Bhattacharya
DIN: 02011213
His	Excellency	Yasir	Othman	H.	AI-Rumayyan
DIN: 09245977
K.V. Chowdary
DIN: 08485334
K.V. Kamath
DIN: 00043501
Haigreve Khaitan
DIN: 00005290
Dinesh Kanabar
DIN: 00003252
Executive
Directors
Chairman and
Managing Director
Non-Executive
Directors

Step 6 — Create the validated ratio table

In [12]:

# FinanceResearchAgent — Step 6
# Structure ratios directly reported in the annual report

import pandas as pd
from pathlib import Path

ratios = [
    {
        "metric": "Current Ratio",
        "fy_2025_26": 0.99,
        "fy_2024_25": 1.05,
        "unit": "ratio",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Debt-Equity Ratio",
        "fy_2025_26": 0.41,
        "fy_2024_25": 0.37,
        "unit": "ratio",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Debt Service Coverage Ratio",
        "fy_2025_26": 4.03,
        "fy_2024_25": 2.06,
        "unit": "ratio",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Return on Equity",
        "fy_2025_26": 8.5,
        "fy_2024_25": 7.3,
        "unit": "%",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Net Profit Margin",
        "fy_2025_26": 8.0,
        "fy_2024_25": 6.3,
        "unit": "%",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Return on Capital Employed",
        "fy_2025_26": 20.7,
        "fy_2024_25": 14.6,
        "unit": "%",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
    {
        "metric": "Return on Investment",
        "fy_2025_26": 9.5,
        "fy_2024_25": 10.3,
        "unit": "%",
        "statement_scope": "Standalone",
        "pdf_page": 93,
    },
]

df_ratios = pd.DataFrame(ratios)

df_ratios["source"] = (
    "RIL Integrated Annual Report FY 2025-26, "
    "Standalone Financial Statements, Note 40"
)

df_ratios["validation_status"] = "Transcribed from source; verify before publication"

output_path = Path(
    "/content/finance_research_output/validated_ratio_candidates.csv"
)

df_ratios.to_csv(output_path, index=False)

display(df_ratios)
print("\nSaved to:", output_path)

,metric,fy_2025_26,fy_2024_25,unit,statement_scope,pdf_page,source,validation_status
0,Current Ratio,0.99,1.05,ratio,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
1,Debt-Equity Ratio,0.41,0.37,ratio,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
2,Debt Service Coverage Ratio,4.03,2.06,ratio,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
3,Return on Equity,8.50,7.30,%,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
4,Net Profit Margin,8.00,6.30,%,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
5,Return on Capital Employed,20.70,14.60,%,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...
6,Return on Investment,9.50,10.30,%,Standalone,93,"RIL Integrated Annual Report FY 2025-26, Stand...",Transcribed from source; verify before publica...

Saved to: /content/finance_research_output/validated_ratio_candidates.csv

Step 7 — Add automated validation

In [13]:

# FinanceResearchAgent — Step 7
# Validate ratio data and calculate year-over-year changes

import pandas as pd
from pathlib import Path

input_path = Path(
    "/content/finance_research_output/validated_ratio_candidates.csv"
)

df = pd.read_csv(input_path)

# Check required fields
required_columns = [
    "metric",
    "fy_2025_26",
    "fy_2024_25",
    "unit",
    "statement_scope",
    "pdf_page",
    "source",
]

missing_columns = [
    col for col in required_columns if col not in df.columns
]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

# Check missing values in important fields
df["missing_data"] = df[required_columns].isna().any(axis=1)

# Calculate absolute and relative changes
df["absolute_change"] = df["fy_2025_26"] - df["fy_2024_25"]

df["change_pct"] = (
    df["absolute_change"]
    / df["fy_2024_25"].replace(0, float("nan"))
) * 100

# Basic range checks for percentage metrics
df["range_check"] = "Not applicable"

percentage_mask = df["unit"].eq("%")

df.loc[percentage_mask, "range_check"] = df.loc[
    percentage_mask, "fy_2025_26"
].apply(
    lambda value: "Pass" if 0 <= value <= 100 else "Review"
)

# Flag rows for review
df["validation_result"] = "Review source"

df.loc[
    ~df["missing_data"] & (df["range_check"] != "Review"),
    "validation_result"
] = "Basic checks passed; source verification required"

output_path = Path(
    "/content/finance_research_output/ratio_validation_results.csv"
)

df.to_csv(output_path, index=False)

display(
    df[
        [
            "metric",
            "fy_2025_26",
            "fy_2024_25",
            "absolute_change",
            "change_pct",
            "missing_data",
            "range_check",
            "validation_result",
        ]
    ].round(2)
)

print("\nValidation results saved to:", output_path)

,metric,fy_2025_26,fy_2024_25,absolute_change,change_pct,missing_data,range_check,validation_result
0,Current Ratio,0.99,1.05,-0.06,-5.71,False,Not applicable,Basic checks passed; source verification required
1,Debt-Equity Ratio,0.41,0.37,0.04,10.81,False,Not applicable,Basic checks passed; source verification required
2,Debt Service Coverage Ratio,4.03,2.06,1.97,95.63,False,Not applicable,Basic checks passed; source verification required
3,Return on Equity,8.50,7.30,1.20,16.44,False,Pass,Basic checks passed; source verification required
4,Net Profit Margin,8.00,6.30,1.70,26.98,False,Pass,Basic checks passed; source verification required
5,Return on Capital Employed,20.70,14.60,6.10,41.78,False,Pass,Basic checks passed; source verification required
6,Return on Investment,9.50,10.30,-0.80,-7.77,False,Pass,Basic checks passed; source verification required

Validation results saved to: /content/finance_research_output/ratio_validation_results.csv

In [ ]:
Step 8 — Build your first reusable research tool

In [14]:

# FinanceResearchAgent — Step 8
# Reusable, source-linked research search tool

import json
import re
from pathlib import Path
from IPython.display import display, Markdown

DATA_PATH = Path(
    "/content/finance_research_output/ril_annual_report_pages.json"
)

with open(DATA_PATH, "r", encoding="utf-8") as f:
    report_pages = json.load(f)


def research_search(question, max_results=5):
    """
    Search extracted annual-report pages for relevant evidence.
    Returns source-linked passages, not AI-generated conclusions.
    """
    if not question or not question.strip():
        raise ValueError("Please enter a research question.")

    if not isinstance(max_results, int) or max_results < 1:
        raise ValueError("max_results must be a positive integer.")

    # Remove common question words and score pages by matching terms.
    stop_words = {
        "what", "which", "when", "where", "why", "how",
        "does", "did", "the", "and", "for", "from",
        "with", "that", "this", "are", "was", "were",
        "explain", "tell", "about", "reliance", "industries"
    }

    terms = [
        word.lower()
        for word in re.findall(r"[A-Za-z0-9]+", question)
        if word.lower() not in stop_words and len(word) > 2
    ]

    if not terms:
        raise ValueError("Please include a specific research topic.")

    results = []

    for page in report_pages:
        text = re.sub(r"\s+", " ", page["text"]).strip()
        lower_text = text.lower()

        score = sum(lower_text.count(term) for term in terms)

        if score == 0:
            continue

        # Find the first matching passage.
        first_match = min(
            (lower_text.find(term) for term in terms
             if lower_text.find(term) >= 0),
            default=0
        )

        start = max(0, first_match - 250)
        end = min(len(text), first_match + 650)

        results.append({
            "score": score,
            "question": question,
            "pdf_page": page["pdf_page"],
            "reporting_period": page["reporting_period"],
            "source_file": page["source_file"],
            "source_url": page["source_url"],
            "evidence": text[start:end]
        })

    results.sort(key=lambda item: item["score"], reverse=True)
    return results[:max_results]


# Test the tool
question = "What explains the change in net profit margin?"

results = research_search(question, max_results=5)

print("Research question:", question)
print("Matching passages:", len(results))

for i, item in enumerate(results, start=1):
    print(f"\n--- Result {i} | PDF page {item['pdf_page']} ---")
    print("Reporting period:", item["reporting_period"])
    print("Source:", item["source_url"])
    print("Evidence:", item["evidence"])

Research question: What explains the change in net profit margin?
Matching passages: 5

--- Result 1 | PDF page 79 ---
Reporting period: FY 2025-26
Source: https://www.ril.com/ar2025-26/index.html
Evidence:  155 Standalone Financial Statements Notes To the Standalone Financial Statements for the year ended 31st March, 2026 % Company/subsidiary is a beneficiary. @@ Entity Merged during the year ^ Relationships established during the year. & Relationship changed from Joint Venture to Subsidiary. $$ Amalgamated with Jiostar India Private Limited. Sr. No. Name of the Subsidiary Companies 43 Den Kashi Cable Network Limited 44 Den Malayalam Telenet Private Limited 45 Den Nashik City Cable Network Private Limited 46 Den Networks Limited 47 Den Premium Multilink Cable Network Private Limited 48 Den Rajkot City Communication Private Limited 49 Den Saya Channel Network Limited 50 Digital Media Distribution Trust% 51 Digital18 Media Private Limited 52 Drashti Cable Network Limited 53 Dronagiri Bokadvira East Infra Limited 54 Dronagiri Bokadvira North Infra Limited 55 Dronagiri Bokadvira South Infra Li

--- Result 2 | PDF page 32 ---
Reporting period: FY 2025-26
Source: https://www.ril.com/ar2025-26/index.html
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 60 61 Corporate Governance Report Listing on Stock Exchanges Name of the stock exchanges Address Equity Shares ISIN: INE002A01018 - BSE Limited (BSE) Scrip Code - 500325 - National Stock Exchange of India Limited (NSE) Trading Symbol - RELIANCE - Phiroze Jeejeebhoy Towers, Dalal Street, Mumbai – 400 001 - Exchange Plaza, C-1, G Block, Bandra-Kurla Complex, Bandra (East), Mumbai – 400 051 Global Depository Receipts (GDRs) - Luxembourg Stock Exchange - 35A Boulevard Joseph II, L-1840, Luxembourg Overseas Depository - The Bank of New York Mellon Corporation - 240, Greenwich Street, New York, NY 10286 Domestic Custodian - ICICI Bank Limited - Empire Complex, 1st Floor, 414, Senapati Bapat Marg, Low

--- Result 3 | PDF page 37 ---
Reporting period: FY 2025-26
Source: https://www.ril.com/ar2025-26/index.html
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 70 71 Corporate Governance Report f) The Securities and Exchange Board of India (Issue and Listing of Non-Convertible Securities) Regulations, 2021; g) The Securities and Exchange Board of India (Share Based Employee Benefits and Sweat Equity) Regulations, 2021; h) The Securities and Exchange Board of India (Delisting of Equity Shares) Regulations, 2021; i) The Securities and Exchange Board of India (Buy-back of Securities) Regulations, 2018. *The Company being a ‘material subsidiary’ of Reliance Industries Limited (“RIL”), as defined in Regulation 16(1) (c) of the SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015, certain employees of the Company have been categorised as Desi

--- Result 4 | PDF page 63 ---
Reporting period: FY 2025-26
Source: https://www.ril.com/ar2025-26/index.html
Evidence: he Company grants stock options to the employees of its subsidiaries, the transactions are accounted by increasing the cost of investment in subsidiary with a corresponding credit in the equity. (j) Foreign Currencies Transactions and T ranslation Exchange gains or losses on foreign currency borrowings taken prior to April 1, 2016 which are related to the acquisition or construction of qualifying assets are adjusted in the carrying cost of such assets. (k) Revenue Recognition Revenue from contracts with customers is recognised when control of the goods or services are transferred to the customer at an amount that reflects the consideration entitled in exchange for those goods or services. The Company is generally the principal as it typically controls the goods or services before transferring them to the customer. Revenue is measured at the amount of consideration which the Company expec

--- Result 5 | PDF page 93 ---
Reporting period: FY 2025-26
Source: https://www.ril.com/ar2025-26/index.html
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 182 183 Standalone Financial Statements Notes To the Standalone Financial Statements for the year ended 31st March, 2026 40. Ratio Analysis: Sr. No. Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 Trade Payables Turnover Ratio 3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -* 47.92 - 9 Net Profit Margin (%) b 8.0% 6.3% 27.0 10 Return on Capital Employed (%) c 20.7% 14.6% 41.0 11 Return on Investment (%) 9.5% 10.3% (7.7) a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year. b) Net Profit Margin increased due to higher net

Step 9 — Improve the research search function

In [15]:

# FinanceResearchAgent — Step 9
# Improved keyword-based evidence retrieval

import json
import re
from pathlib import Path

DATA_PATH = Path(
    "/content/finance_research_output/ril_annual_report_pages.json"
)

with open(DATA_PATH, "r", encoding="utf-8") as f:
    report_pages = json.load(f)


def research_search_v2(question, max_results=5):
    if not question or not question.strip():
        raise ValueError("Enter a research question.")

    q = question.lower()

    # Topic-specific terms and phrases
    topic_rules = {
        "net profit margin": [
            "net profit margin",
            "higher net profit",
            "8.0%",
            "6.3%"
        ],
        "debt service coverage ratio": [
            "debt service coverage ratio",
            "finance cost",
            "principal repayments"
        ],
        "return on capital employed": [
            "return on capital employed",
            "20.7%",
            "14.6%"
        ]
    }

    selected_topic = next(
        (topic for topic in topic_rules if topic in q),
        None
    )

    if selected_topic is None:
        terms = [
            t for t in re.findall(r"[a-z0-9]+", q)
            if len(t) > 2
        ]
    else:
        terms = topic_rules[selected_topic]

    results = []

    for page in report_pages:
        text = re.sub(r"\s+", " ", page["text"]).strip()
        lower_text = text.lower()

        score = 0

        for term in terms:
            if term in lower_text:
                score += 5 if " " in term else 1

        # Prefer the standalone ratio-analysis page for
        # questions about reported standalone financial ratios.
        if selected_topic and "ratio analysis" in lower_text:
            score += 10

        if score == 0:
            continue

        results.append({
            "score": score,
            "pdf_page": page["pdf_page"],
            "source_url": page["source_url"],
            "evidence": text[:1800]
        })

    results.sort(
        key=lambda x: (x["score"], -x["pdf_page"]),
        reverse=True
    )

    return results[:max_results]


question = "What explains the change in net profit margin?"
results = research_search_v2(question, max_results=3)

print("Question:", question)
print("Relevant pages found:", len(results))

for result in results:
    print(f"\nPDF page: {result['pdf_page']}")
    print("Relevance score:", result["score"])
    print("Source:", result["source_url"])
    print("Evidence:\n", result["evidence"])

Question: What explains the change in net profit margin?
Relevant pages found: 3

PDF page: 93
Relevance score: 22
Source: https://www.ril.com/ar2025-26/index.html
Evidence:
 Reliance Industries Limited Integrated Annual Report 2025-26 182 183 Standalone Financial Statements Notes To the Standalone Financial Statements for the year ended 31st March, 2026 40. Ratio Analysis: Sr. No. Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 Trade Payables Turnover Ratio 3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -* 47.92 - 9 Net Profit Margin (%) b 8.0% 6.3% 27.0 10 Return on Capital Employed (%) c 20.7% 14.6% 41.0 11 Return on Investment (%) 9.5% 10.3% (7.7) a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year. b) Net Profit Margin increased due to higher net profit. c) Return on Capital Employed increased due to higher profit and reduction in capital employed. * Net working capital is negative. 40.1 Formula for computation of ratios are as follows: Sr. No. Particulars Formula 1 Current Ratio Current Assets Current Liabilities 2 Debt-Equity Ratio Total Debt Total Equity 3 Debt Service Coverage Ratio Earnings before Interest and Tax Interest Expense + Principal Repayments made during the year for long term loans 4 Return on Equity (%) Profit After Tax Average Net Worth 5 Inventory Turnover Ratio Cost of Goods Sold (Cost of Material Consumed + Purchases + Changes in Inventory + Manufacturing Expenses) Average Inventories of Finished Goods, Stock‑in‑Process and Stock-in-Trade 6 Trade Receivables Turnover Ratio Value of Sales & Services Average Trade Receivables 7 Trade Payables Turnover Ratio Cost of Materials Consumed (after adjustment of RM Inventory)

PDF page: 6
Relevance score: 12
Source: https://www.ril.com/ar2025-26/index.html
Evidence:
 Reliance Industries Limited Integrated Annual Report 2025-26 8 9 Management Discussion and Analysis - Business OverviewManagement Discussion and Analysis Movement in Key Financial Ratios The Debt Service Coverage Ratio increased from 2.06 in FY 2024-25 to 4.03 in FY 2025-26, due to lower finance cost and principal repayments of loans during the year. The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit. Return on Capital Employed increased from 14.6% in FY 2024-25 to 20.7% in FY 2025-26, due to higher profit and reduction in capital employed. Long Term Debt to Working Capital increased from 7.53 in FY 2024-25 to 17.12 in FY 2025-26, due to higher debt and efficient working capital management. Interest Coverage Ratio increased from 5.59 in FY 2024-25 to 8.83 in FY 2025-26, due to higher operating profit along with lower finance costs. The Return on Net Worth* improved to 10.1% in FY 2025-26 as against 8.2% in previous year due to increase in net profit during the year. *Adjusted for CWIP and revaluation Liquidity and Capital Resources Macro Environment FY 2025-26 saw heightened volatility in financial markets amid tariff uncertainty and global geopolitics. In India, the first half of the financial year saw RBI easing monetary policy leading to an environment of softening domestic yields with 10y G-sec yields easing towards 6.25%. The second half of the year saw yields reversing upwards as RBI shifted its stance from accommodative to neutral, causing 10y G-sec yields to harden towards 7%. Rupee came under downward pressure on account of FPI outflows, rising trade deficit and fresh tensions in Middle East. Fund Raising The year 2025 unfolded against a backdrop of heightened market fluctuations. Trade dynamics shifted as US

PDF page: 5
Relevance score: 5
Source: https://www.ril.com/ar2025-26/index.html
Evidence:
 Reliance Industries Limited Integrated Annual Report 2025-26 6 7 Management Discussion and Analysis Financial Performance and Review Operating Environment Global economic expansion continued, with IMF estimating global growth at 3.4% for CY25, improving from CY24 growth of 3.1%. Inflationary pressures have moderated marginally across many economies but remained sticky, reflecting evolving trade dynamics and an uptick in key commodity prices. Central banks across major economies continued their easing cycle but adopted a more cautious stance towards the end of CY25, signalling the likely end of policy easing cycle. Despite these stabilising trends, trade uncertainties, and ongoing regional conflicts continued to weigh on market sentiment, global trade flows, and investment decisions. End of Fiscal 2026 saw significant supply-side disruptions in energy markets from the Middle East conflict, leading to spike in energy prices. Brent crude prices rose from $70/bbl towards $100/bbl, posing fresh stagflationary risks for the global economy. The Indian economy is estimated to grow at 7.6% in FY 2025-26, up from 7.1% in FY 2024-25, as RBI rate cuts along with cuts in personal tax and GST led to recovery in consumption demand. Supportive inflation backdrop led RBI to ease policy rates by 100 bps in FY 2025-26. RBI also enhanced liquidity through measures like CRR Cuts, bond purchases and long-term FX swaps. Depreciation pressure on Rupee intensified during second half on back of foreign portfolio outflows and surge in crude oil prices. At the end, Rupee registered the largest annual depreciation against Dollar to close the year at around 95 levels. Total India oil demand was at 243.2 MMT, growing 1.7% on a Y-o-Y basis, led by transportation fuels. Mobile data traffic in India is

Next step: make the answer more useful

In [16]:
def answer_research_question(question):
    results = research_search_v2(question)

    if not results:
        return {
            "question": question,
            "answer": "Insufficient evidence found in the available source.",
            "sources": []
        }

    question_lower = question.lower()

    if "net profit margin" in question_lower:
        answer = (
            "Reliance Industries Limited's standalone net profit margin "
            "increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, "
            "an improvement of 1.7 percentage points. The annual report "
            "attributes the increase to higher net profit. The report "
            "does not establish the specific underlying drivers in this passage."
        )
    else:
        answer = (
            "Relevant source passages were found. Review the evidence "
            "before drawing a conclusion."
        )

    return {
        "question": question,
        "answer": answer,
        "sources": [
            {
                "pdf_page": result["pdf_page"],
                "source_url": result["source_url"],
                "evidence": result["evidence"]
            }
            for result in results[:2]
        ]
    }


result = answer_research_question(
    "What explains the change in net profit margin?"
)

print("QUESTION:", result["question"])
print("\nANSWER:", result["answer"])
print("\nSOURCES:")

for source in result["sources"]:
    print(f"\nPDF page: {source['pdf_page']}")
    print("Source:", source["source_url"])
    print("Evidence:", source["evidence"][:500])

QUESTION: What explains the change in net profit margin?

ANSWER: Reliance Industries Limited's standalone net profit margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, an improvement of 1.7 percentage points. The annual report attributes the increase to higher net profit. The report does not establish the specific underlying drivers in this passage.

SOURCES:

PDF page: 93
Source: https://www.ril.com/ar2025-26/index.html
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 182 183 Standalone Financial Statements Notes To the Standalone Financial Statements for the year ended 31st March, 2026 40. Ratio Analysis: Sr. No. Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 T

PDF page: 6
Source: https://www.ril.com/ar2025-26/index.html
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 8 9 Management Discussion and Analysis - Business OverviewManagement Discussion and Analysis Movement in Key Financial Ratios The Debt Service Coverage Ratio increased from 2.06 in FY 2024-25 to 4.03 in FY 2025-26, due to lower finance cost and principal repayments of loans during the year. The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit. Return on Capital Employed increased from

In [ ]:
Next step: improve evidence extraction

In [17]:

import re

def extract_relevant_sentences(question, evidence, max_sentences=4):
    """Extract source sentences that best match a research question."""

    question_terms = set(
        re.findall(r"[a-zA-Z]+", question.lower())
    )

    sentences = re.split(r"(?<=[.!?])\s+", evidence)
    scored_sentences = []

    for sentence in sentences:
        sentence_lower = sentence.lower()
        score = sum(
            1 for term in question_terms
            if term in sentence_lower
        )

        if score > 0:
            scored_sentences.append((score, sentence.strip()))

    scored_sentences.sort(key=lambda item: item[0], reverse=True)

    return [
        sentence
        for score, sentence in scored_sentences[:max_sentences]
    ]


question = "What explains the change in net profit margin?"
results = research_search_v2(question)

for result in results[:2]:
    print(f"\nPDF page: {result['pdf_page']}")

    relevant = extract_relevant_sentences(
        question,
        result["evidence"]
    )

    for sentence in relevant:
        print("-", sentence)

PDF page: 93
- Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 Trade Payables Turnover Ratio 3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -* 47.92 - 9 Net Profit Margin (%) b 8.0% 6.3% 27.0 10 Return on Capital Employed (%) c 20.7% 14.6% 41.0 11 Return on Investment (%) 9.5% 10.3% (7.7) a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year.
- Particulars Formula 1 Current Ratio Current Assets Current Liabilities 2 Debt-Equity Ratio Total Debt Total Equity 3 Debt Service Coverage Ratio Earnings before Interest and Tax Interest Expense + Principal Repayments made during the year for long term loans 4 Return on Equity (%) Profit After Tax Average Net Worth 5 Inventory Turnover Ratio Cost of Goods Sold (Cost of Material Consumed + Purchases + Changes in Inventory + Manufacturing Expenses) Average Inventories of Finished Goods, Stock‑in‑Process and Stock-in-Trade 6 Trade Receivables Turnover Ratio Value of Sales & Services Average Trade Receivables 7 Trade Payables Turnover Ratio Cost of Materials Consumed (after adjustment of RM Inventory)
- b) Net Profit Margin increased due to higher net profit.
- Reliance Industries Limited Integrated Annual Report 2025-26 182 183 Standalone Financial Statements Notes To the Standalone Financial Statements for the year ended 31st March, 2026 40.

PDF page: 6
- The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit.
- The Return on Net Worth* improved to 10.1% in FY 2025-26 as against 8.2% in previous year due to increase in net profit during the year.
- In India, the first half of the financial year saw RBI easing monetary policy leading to an environment of softening domestic yields with 10y G-sec yields easing towards 6.25%.
- Reliance Industries Limited Integrated Annual Report 2025-26 8 9 Management Discussion and Analysis - Business OverviewManagement Discussion and Analysis Movement in Key Financial Ratios The Debt Service Coverage Ratio increased from 2.06 in FY 2024-25 to 4.03 in FY 2025-26, due to lower finance cost and principal repayments of loans during the year.

create a metric-focused evidence extractor

In [18]:

def get_metric_evidence(question, results):
    question_lower = question.lower()

    metric_rules = {
        "net profit margin": [
            "net profit margin",
            "higher net profit"
        ],
        "debt service coverage ratio": [
            "debt service coverage ratio",
            "finance cost",
            "principal repayments"
        ],
        "return on capital employed": [
            "return on capital employed",
            "reduction in capital employed",
            "higher profit"
        ]
    }

    selected_metric = next(
        (
            metric for metric in metric_rules
            if metric in question_lower
        ),
        None
    )

    if selected_metric is None:
        return {
            "status": "needs_review",
            "message": "No metric-specific rule found.",
            "evidence": []
        }

    keywords = metric_rules[selected_metric]
    matches = []

    for result in results:
        text = result["evidence"]
        sentences = re.split(r"(?<=[.!?])\s+", text)

        for sentence in sentences:
            sentence_lower = sentence.lower()

            if (
                selected_metric in sentence_lower
                or (
                    "net profit margin" in selected_metric
                    and "net profit margin" in sentence_lower
                )
            ):
                matches.append({
                    "pdf_page": result["pdf_page"],
                    "source_url": result["source_url"],
                    "evidence": sentence.strip()
                })

    return {
        "status": "evidence_found" if matches else "needs_review",
        "metric": selected_metric,
        "evidence": matches
    }


question = "What explains the change in net profit margin?"
evidence_result = get_metric_evidence(question, results)

print("Status:", evidence_result["status"])
print("Metric:", evidence_result.get("metric", "Not identified"))

for item in evidence_result["evidence"]:
    print("\nPDF page:", item["pdf_page"])
    print("Evidence:", item["evidence"])
    print("Source:", item["source_url"])

Status: evidence_found
Metric: net profit margin

PDF page: 93
Evidence: Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 Trade Payables Turnover Ratio 3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -* 47.92 - 9 Net Profit Margin (%) b 8.0% 6.3% 27.0 10 Return on Capital Employed (%) c 20.7% 14.6% 41.0 11 Return on Investment (%) 9.5% 10.3% (7.7) a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 93
Evidence: b) Net Profit Margin increased due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 6
Evidence: The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

extract only the relevant evidence

In [19]:

def get_clean_metric_evidence(question, results):
    question_lower = question.lower()

    metric_rules = {
        "net profit margin": [
            "net profit margin increased from",
            "net profit margin increased due to"
        ],
        "debt service coverage ratio": [
            "debt service coverage ratio increased from",
            "debt service coverage ratio increased due to"
        ],
        "return on capital employed": [
            "return on capital employed increased from",
            "return on capital employed increased due to"
        ]
    }

    selected_metric = next(
        (metric for metric in metric_rules if metric in question_lower),
        None
    )

    if selected_metric is None:
        return {
            "status": "needs_review",
            "message": "Metric not supported by current rules.",
            "evidence": []
        }

    matches = []

    for result in results:
        text = result["evidence"]
        sentences = re.split(r"(?<=[.!?])\s+", text)

        for sentence in sentences:
            sentence_lower = sentence.lower()

            if any(
                phrase in sentence_lower
                for phrase in metric_rules[selected_metric]
            ):
                matches.append({
                    "pdf_page": result["pdf_page"],
                    "evidence": sentence.strip(),
                    "source_url": result["source_url"]
                })

    # Remove duplicate evidence while preserving source references.
    unique_matches = []
    seen = set()

    for match in matches:
        key = (match["pdf_page"], match["evidence"])

        if key not in seen:
            seen.add(key)
            unique_matches.append(match)

    return {
        "status": "evidence_found" if unique_matches else "needs_review",
        "metric": selected_metric,
        "evidence": unique_matches
    }


question = "What explains the change in net profit margin?"
clean_result = get_clean_metric_evidence(question, results)

print("Status:", clean_result["status"])
print("Metric:", clean_result.get("metric", "Not identified"))

for item in clean_result["evidence"]:
    print("\nPDF page:", item["pdf_page"])
    print("Evidence:", item["evidence"])
    print("Source:", item["source_url"])

Status: evidence_found
Metric: net profit margin

PDF page: 93
Evidence: b) Net Profit Margin increased due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 6
Evidence: The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

build the research answer pipeline

In [20]:

def run_finance_research(question):
    # Step 1: Retrieve relevant report pages
    search_results = research_search_v2(question)

    # Step 2: Extract evidence for supported metrics
    evidence_result = get_clean_metric_evidence(
        question,
        search_results
    )

    # Step 3: Check whether evidence is sufficient
    if evidence_result["status"] != "evidence_found":
        return {
            "question": question,
            "status": "needs_review",
            "answer": (
                "The current research rules could not find sufficient "
                "metric-specific evidence. Manual review is required."
            ),
            "sources": []
        }

    # Step 4: Generate a grounded answer for supported metrics
    metric = evidence_result["metric"]
    evidence = evidence_result["evidence"]

    if metric == "net profit margin":
        answer = (
            "Reliance Industries Limited's standalone net profit margin "
            "increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, "
            "an increase of 1.7 percentage points. The annual report "
            "attributes the improvement to higher net profit."
        )
    elif metric == "debt service coverage ratio":
        answer = (
            "The annual report states that the debt service coverage "
            "ratio increased due to lower finance costs and principal "
            "repayments of loans during the year."
        )
    elif metric == "return on capital employed":
        answer = (
            "The annual report attributes the increase in return on "
            "capital employed to higher profit and a reduction in "
            "capital employed."
        )
    else:
        answer = "Manual review is required."

    # Step 5: Return answer and its supporting evidence
    return {
        "question": question,
        "status": "evidence_found",
        "answer": answer,
        "sources": evidence
    }


report = run_finance_research(
    "What explains the change in net profit margin?"
)

print("QUESTION:", report["question"])
print("\nSTATUS:", report["status"])
print("\nANSWER:", report["answer"])
print("\nSUPPORTING EVIDENCE:")

for source in report["sources"]:
    print(f"\nPDF page: {source['pdf_page']}")
    print("Evidence:", source["evidence"])
    print("Source:", source["source_url"])

QUESTION: What explains the change in net profit margin?

STATUS: evidence_found

ANSWER: Reliance Industries Limited's standalone net profit margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, an increase of 1.7 percentage points. The annual report attributes the improvement to higher net profit.

SUPPORTING EVIDENCE:

PDF page: 93
Evidence: b) Net Profit Margin increased due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 6
Evidence: The Net Profit Margin increased from 6.3% in FY 2024-25 to 8.0% in FY 2025-26, due to higher net profit.
Source: https://www.ril.com/ar2025-26/index.html

test a second metric

In [21]:

test_question = "Why did the debt service coverage ratio increase?"

test_report = run_finance_research(test_question)

print("QUESTION:", test_report["question"])
print("\nSTATUS:", test_report["status"])
print("\nANSWER:", test_report["answer"])
print("\nSUPPORTING EVIDENCE:")

for source in test_report["sources"]:
    print(f"\nPDF page: {source['pdf_page']}")
    print("Evidence:", source["evidence"])
    print("Source:", source["source_url"])

QUESTION: Why did the debt service coverage ratio increase?

STATUS: evidence_found

ANSWER: The annual report states that the debt service coverage ratio increased due to lower finance costs and principal repayments of loans during the year.

SUPPORTING EVIDENCE:

PDF page: 93
Evidence: Particulars 2025-26 2024-25 % Changes 1 Current Ratio 0.99 1.05 (5.7) 2 Debt-Equity Ratio 0.41 0.37 10.8 3 Debt Service Coverage Ratio a 4.03 2.06 95.6 4 Return on Equity (%) 8.5% 7.3% 17.0 5 Inventory Turnover Ratio 5.91 6.85 (13.7) 6 Trade Receivables Turnover Ratio 33.93 36.74 (7.6) 7 Trade Payables Turnover Ratio 3.39 3.61 (6.1) 8 Net Capital Turnover Ratio -* 47.92 - 9 Net Profit Margin (%) b 8.0% 6.3% 27.0 10 Return on Capital Employed (%) c 20.7% 14.6% 41.0 11 Return on Investment (%) 9.5% 10.3% (7.7) a) Debt Service Coverage Ratio increased due to lower finance cost and principal repayments of loans during the year.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 6
Evidence: Reliance Industries Limited Integrated Annual Report 2025-26 8 9 Management Discussion and Analysis - Business OverviewManagement Discussion and Analysis Movement in Key Financial Ratios The Debt Service Coverage Ratio increased from 2.06 in FY 2024-25 to 4.03 in FY 2025-26, due to lower finance cost and principal repayments of loans during the year.
Source: https://www.ril.com/ar2025-26/index.html

test a third metric — Return on Capital Employed (ROCE)

In [22]:

test_question = "What explains the increase in return on capital employed?"

test_report = run_finance_research(test_question)

print("QUESTION:", test_report["question"])
print("\nSTATUS:", test_report["status"])
print("\nANSWER:", test_report["answer"])
print("\nSUPPORTING EVIDENCE:")

for source in test_report["sources"]:
    print(f"\nPDF page: {source['pdf_page']}")
    print("Evidence:", source["evidence"])
    print("Source:", source["source_url"])

QUESTION: What explains the increase in return on capital employed?

STATUS: evidence_found

ANSWER: The annual report attributes the increase in return on capital employed to higher profit and a reduction in capital employed.

SUPPORTING EVIDENCE:

PDF page: 93
Evidence: c) Return on Capital Employed increased due to higher profit and reduction in capital employed.
Source: https://www.ril.com/ar2025-26/index.html

PDF page: 6
Evidence: Return on Capital Employed increased from 14.6% in FY 2024-25 to 20.7% in FY 2025-26, due to higher profit and reduction in capital employed.
Source: https://www.ril.com/ar2025-26/index.html

make the agent more reliable

In [23]:

def validate_research_evidence(metric, evidence_items):
    explanation_phrases = {
        "net profit margin": [
            "higher net profit"
        ],
        "debt service coverage ratio": [
            "lower finance cost",
            "principal repayments"
        ],
        "return on capital employed": [
            "higher profit",
            "reduction in capital employed"
        ]
    }

    metric = metric.lower()

    if metric not in explanation_phrases:
        return {
            "status": "needs_review",
            "reason": "No validation rule exists for this metric."
        }

    relevant_items = []

    for item in evidence_items:
        text = item["evidence"].lower()

        has_metric = metric in text
        has_explanation = any(
            phrase in text
            for phrase in explanation_phrases[metric]
        )

        if has_metric and has_explanation:
            relevant_items.append(item)

    return {
        "status": (
            "validated" if relevant_items else "needs_review"
        ),
        "metric": metric,
        "evidence": relevant_items,
        "reason": (
            "Metric and explanatory wording found in source text."
            if relevant_items
            else "Supporting explanation was not found."
        )
    }


validation = validate_research_evidence(
    "return on capital employed",
    test_report["sources"]
)

print("Validation status:", validation["status"])
print("Reason:", validation["reason"])

for item in validation.get("evidence", []):
    print("\nPDF page:", item["pdf_page"])
    print("Evidence:", item["evidence"])

Validation status: validated
Reason: Metric and explanatory wording found in source text.

PDF page: 93
Evidence: c) Return on Capital Employed increased due to higher profit and reduction in capital employed.

PDF page: 6
Evidence: Return on Capital Employed increased from 14.6% in FY 2024-25 to 20.7% in FY 2025-26, due to higher profit and reduction in capital employed.

In [24]:
from pathlib import Path

print("Notebook environment:", Path("/content").exists())
print("\nResearch output files:")

output_dir = Path("/content/finance_research_output")

if output_dir.exists():
    for file in sorted(output_dir.iterdir()):
        if file.is_file():
            print(f"{file.name} — {file.stat().st_size:,} bytes")
else:
    print("Research output folder not found.")

Notebook environment: True

Research output files:
financial_metric_evidence.csv — 9,012 bytes
financial_metric_evidence_v2.csv — 8,266 bytes
ratio_validation_results.csv — 2,141 bytes
ril_annual_report_pages.json — 1,056,895 bytes
validated_ratio_candidates.csv — 1,361 bytes